language: generic 
#tell travis that we need superuser permissions
sudo: required
services:
    - docker

before_install:
    - docker build -t erolhira/onlyweb -f ./onlyweb/Dockerfile ./onlyweb

script:
    - docker run erolhira/onlyweb npm run test -- --coverage

before_deploy:
    - cd onlyweb

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-onlyweb"
    env: "DockerOnlyweb-env"
    bucket_name: "elasticbeanstalk-eu-central-1-544214107792"
    bucket_path: "docker-onlyweb"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

#bucket_name: the S3 bucket where to put project files
#bucket_path: the directory path that will be created under S3 bucket to put the files in.
